### ISSUE TITLE
Possible to view / edit interface configuration?

### ISSUE THREAD

**Issue by dbjungle** [mihakralj/opnsense-cli#6]
I've noticed when I try to view a specific interface it seems to have no effect.  I receive more details if I output to yaml, but I'm still unable to do a specific interface.  Further more changing one of these aspects (dhcphostname on wan for example) seems to have no effect.

```
root@DE1FW01:~ # opnsense show interfaces 
   opnsense: {
       interfaces: {
           wan: {…}
           lan: {…}
           lo0: {…}
       }
   }

root@DE1FW01:~ # opnsense show interfaces wan
   opnsense: {
       interfaces: {
           wan: {…}
           lan: {…}
           lo0: {…}
       }
   }

root@DE1FW01:~ # opnsense -y show interfaces wan
opnsense:
    interfaces:
        lan:
            enable: "1"
            if: vtnet1
            ipaddr: 10.1.4.2
            ipaddrv6: track6
            media: ""
            mediaopt: ""
            subnet: "24"
            subnetv6: "64"
            track6-interface: wan
            track6-prefix-id: "0"
        lo0:
            descr: Loopback
            enable: "1"
            if: lo0
            internal_dynamic: "1"
            ipaddr: 127.0.0.1
            ipaddrv6: ::1
            subnet: "8"
            subnetv6: "128"
            type: none
            virtual: "1"
        wan:
            dhcp6-ia-pd-len: "0"
            dhcphostname: DE1FW01
            enable: "1"
            gateway: WAN_GW
            if: vtnet0
            ipaddr: dhcp
            ipaddrv6: dhcp6
            media: ""
            mediaopt: ""

root@DE1FW01:~ # 

```

Is there something I'm doing wrong?
